version: '3'
services:
  web:
    image: registry.gitlab.com/promises/deployment/webapp-vue:$WEBAPP_VUE_VERSION
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
  reverse-proxy:
    image: registry.gitlab.com/promises/deployment/reverse-proxy:$REVERSE_PROXY_VERSION
    restart: unless-stopped
    ports: 
    - "5002:5002"
    links:
    - api-server
  api-server:
    image: registry.gitlab.com/promises/deployment/api-server:$API_SERVER_VERSION
    restart: unless-stopped
    expose:
    - "8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TOKEN_DB=1
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT=5433
      - POSTGRES_POOL_MIN_CONN=10
      - POSTGRES_POOL_MAX_CONN=100
      - SENTRY_DSN
    extra_hosts:
      - "nova-cloud-controller.maas:172.20.0.14"
      - "keystone.maas:172.20.0.13" 
      - "cinder.maas:172.20.0.19" 
      - "glance.maas:172.20.0.20" 
      - "neutron-api.maas:172.20.0.17" 
      - "heat.maas:172.20.0.18" 
    links:
      - redis
  redis:
    restart: unless-stopped
    image: redis:3.2
    expose: 
      - "6379"
    
